import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Lang = 'en' | 'zh';

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: 'en',
  setLang: () => {},
  t: (key: string) => key,
});

const translations: Record<Lang, Record<string, string>> = {
  en: {
    // Sidebar
    'admin.title': 'Admin Panel',
    'admin.logout': 'Logout',
    'menu.dashboard': 'Dashboard',
    'menu.overview': 'Overview',
    'menu.traffic': 'Traffic',
    'menu.sales': 'Sales',
    'menu.products': 'Products',
    'menu.banners': 'Banners',
    'menu.categories': 'Categories',
    'menu.users': 'Users',
    'menu.reviews': 'Reviews',
    'menu.payments': 'Payments',
    'menu.admins': 'Admins',

    // Common
    'common.save': 'Save',
    'common.saveChanges': 'Save Changes',
    'common.saving': 'Saving...',
    'common.saved': 'Saved',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.search': 'Search...',
    'common.loading': 'Loading...',
    'common.actions': 'Actions',
    'common.status': 'Status',
    'common.name': 'Name',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.back': 'Back',
    'common.create': 'Create',
    'common.upload': 'Upload',
    'common.remove': 'Remove',
    'common.confirm': 'Confirm',
    'common.total': 'Total',
    'common.date': 'Date',
    'common.amount': 'Amount',
    'common.close': 'Close',
    'common.noData': 'No Data',
    'common.na': 'N/A',
    'common.enable': 'Enable',
    'common.disable': 'Disable',
    'common.deactivate': 'Deactivate',
    'common.activate': 'Activate',
    'common.more': 'More',
    'common.uploading': 'Uploading...',
    'common.operationFailed': 'Operation failed:',
    'common.previous': 'Previous',
    'common.next': 'Next',
    'common.pageOf': 'Page {current} of {total}',
    'common.totalItems': 'Total {total} items',
    'common.perPage': 'Per page:',
    'common.allCategories': 'All Categories',
    'common.image': 'Image',
    'common.sortOrder': 'Sort Order',
    'common.enabled': 'Enabled',
    'common.disabled': 'Disabled',
    'common.testMode': 'Test Mode',
    'common.editSettings': 'Edit Settings',
    'common.editSettingsFor': 'Edit {name} Settings',
    'common.cover': 'Cover',
    'common.moveLeft': 'Move left',
    'common.moveRight': 'Move right',
    'common.moveUp': 'Move up',
    'common.moveDown': 'Move down',
    'common.preview': 'Preview',
    'common.copyLink': 'Copy Link',

    // Dashboard / Traffic
    'dashboard.title': 'Traffic Dashboard',
    'dashboard.statsTime': 'Stats Time',
    'dashboard.realtime': 'Realtime',
    'dashboard.7days': '7 Days',
    'dashboard.30days': '30 Days',
    'dashboard.day': 'Day',
    'dashboard.week': 'Week',
    'dashboard.month': 'Month',
    'dashboard.exportData': 'Export Data',
    'dashboard.trafficOverview': 'Traffic Overview',
    'dashboard.visitorAnalysis': 'Visitor Analysis >',
    'dashboard.timeTrend': 'Time Trend',
    'dashboard.allDevices': 'All Devices',
    'dashboard.visitors': 'Visitors',
    'dashboard.productViews': 'Product Views',
    'dashboard.productVisitors': 'Product Visitors',
    'dashboard.conversion': 'Conversion',
    'dashboard.payingCustomers': 'Paying Customers',
    'dashboard.storeFollowers': 'Store Followers',
    'dashboard.liveVisitors': 'Live Visitors',
    'dashboard.live': 'Live',
    'dashboard.shortVideo': 'Short Video',
    'dashboard.video': 'Video',
    'dashboard.imageText': 'Image/Text',
    'dashboard.storePage': 'Store Page',
    'dashboard.trafficSources': 'Traffic Sources',
    'dashboard.topProducts': 'Top Products TOP10',
    'dashboard.trend24h': '24h Traffic Trend',
    'dashboard.people': 'people',
    'dashboard.vsYesterday': 'vs same time yesterday',
    'dashboard.vsPreviousDay': 'vs previous day',
    'dashboard.pageViews': 'Page Views',
    'dashboard.avgPagesSession': 'Avg Pages/Session',
    'dashboard.returningVisitors': 'Returning Visitors',
    'dashboard.newVisitors': 'New Visitors',

    // Users
    'users.title': 'User Management',
    'users.totalUsers': 'Total Users',
    'users.newThisMonth': 'New This Month',
    'users.activeUsers': 'Active Users',
    'users.searchPlaceholder': 'Search users...',
    'users.username': 'Username',
    'users.email': 'Email',
    'users.phone': 'Phone',
    'users.registered': 'Registered',
    'users.role': 'Role',

    // Products
    'products.title': 'Product Management',
    'products.addProduct': 'Add Product',
    'products.editProduct': 'Edit Product',
    'products.searchPlaceholder': 'Search products...',
    'products.productInfo': 'Product Info',
    'products.category': 'Category',
    'products.selectCategory': 'Select Category',
    'products.stock': 'Stock',
    'products.price': 'Price',
    'products.sales': 'Sales',
    'products.basicInfo': 'Basic Information',
    'products.pricing': 'Pricing',
    'products.images': 'Product Images',
    'products.noImages': 'No images',
    'products.noImage': 'No Image',
    'products.features': 'Features',
    'products.featurePlaceholder': 'Feature description',
    'products.addFeature': '+ Add Feature',
    'products.boxContents': 'Box Contents',
    'products.boxContentPlaceholder': 'Item name',
    'products.addBoxItem': '+ Add Item',
    'products.detailContent': 'Detail Content',
    'products.saveDetails': 'Save Details',
    'products.editDetails': 'Edit Details',
    'products.noProducts': 'No products found',
    'products.productName': 'Product Name',
    'products.slug': 'Slug',
    'products.priceCny': 'Price (CNY ¥)',
    'products.originalPriceCny': 'Original Price (CNY ¥)',
    'products.shortDescription': 'Short Description',
    'products.description': 'Description',
    'products.fullDescription': 'Full Description',
    'products.shortDescPlaceholder': 'Brief product summary...',
    'products.descPlaceholder': 'Detailed product description...',
    'products.uploadImages': 'Upload Images',
    'products.imagesUploaded': 'images uploaded',
    'products.deleteImage': 'Delete Image',
    'products.imageNumber': 'Image {n}',
    'products.priceHint': 'Enter price in CNY, auto-convert to USD for storage',
    'products.fetchingRate': 'Fetching rate...',
    'products.ratePreview': '1 CNY ≈ {rate} USD',
    'products.refetchRate': 'Retry',
    'products.cnyPlaceholder': 'CNY amount',
    'products.usdPreview': '≈ ${amount} USD',
    'products.confirmDelete': 'Are you sure you want to delete this product?',
    'products.confirmBatchDelete': 'Are you sure you want to delete {count} selected product(s)? This cannot be undone.',
    'products.batchDeleteFailed': 'Batch delete failed:',
    'products.selectedCount': '{count} item(s) selected',
    'products.deleteSelected': 'Delete Selected ({count})',
    'products.uploadFailed': 'Upload failed:',
    'products.imageError': 'Error',
    'products.active': 'Active',
    'products.totalStock': 'Total Stock',
    'products.totalSales': 'Total Sales',
    'products.createdAt': 'Created At',
    'products.inStock': 'In Stock',
    'products.totalProducts': 'Total {count} products',
    'products.perPageOption': '{n} per page',
    'products.id': 'ID:',
    'products.imagesCount': 'img',
    'products.featuresCount': 'feat',
    'products.productNotFound': 'Product not found',
    'products.requiredFields': 'Please fill in required fields (Name, Slug, Price)',
    'products.detailSaveFailed': 'Detail content save failed: ',
    'products.visibleToCustomers': 'Visible to customers',
    'products.hiddenFromStore': 'Hidden from store',
    'products.uploadedCount': '{count} uploaded',
    'products.clickToUploadImages': 'Click to upload product images',
    'products.imageUploadHint': 'PNG, JPG, GIF up to 5MB each',
    'products.itemsCount': '{count} items',
    'products.imageBlock': 'Image Block',
    'products.textBlock': 'Text Block',
    'products.blocksCount': '{count} blocks',
    'products.addImageBlock': 'Add Image Block',
    'products.addTextBlock': 'Add Text Block',
    'products.clickUploadImage': 'Click to upload image',
    'products.featureIndex': 'Feature {n}',
    'products.boxItemIndex': 'Box item {n}',
    'common.saveFailed': 'Save failed: ',

    // Orders
    'orders.title': 'Sales Analysis',
    'orders.searchPlaceholder': 'Search orders...',
    'orders.orderNo': 'Order No.',
    'orders.customer': 'Customer',
    'orders.amount': 'Amount',
    'orders.pcs': 'pcs',
    'orders.paid': '✓ Paid',
    'orders.unpaid': '○ Unpaid',
    'orders.orderPrefix': 'Order:',
    'orders.customerLabel': 'Customer:',
    'orders.emailLabel': 'Email:',
    'orders.phoneLabel': 'Phone:',
    'orders.addressLabel': 'Address:',
    'orders.amountLabel': 'Amount:',
    'orders.paymentLabel': 'Payment:',
    'orders.updateStatus': 'Update Order Status',
    'orders.updatePaymentStatus': 'Update Payment Status',
    'orders.markPaid': '✓ Mark as Paid',
    'orders.markUnpaid': '○ Mark as Unpaid',
    'orders.pending': 'Pending',
    'orders.confirmed': 'Confirmed',
    'orders.completed': 'Completed',
    'orders.cancelled': 'Cancelled',

    // Banners
    'banners.title': 'Banner Management',
    'banners.addBanner': 'Add Banner',
    'banners.editBanner': 'Edit Banner',
    'banners.titleLabel': 'Title',
    'banners.subtitleLabel': 'Subtitle',
    'banners.imageUrl': 'Image URL',
    'banners.link': 'Link',
    'banners.sortOrderLabel': 'Sort Order',
    'banners.confirmDelete': 'Are you sure you want to delete this banner?',

    // Categories
    'categories.title': 'Category Management',
    'categories.addCategory': 'Add Category',
    'categories.editCategory': 'Edit Category',
    'categories.categoryImage': 'Category Image',
    'categories.clickUpload': 'Click to upload image',
    'categories.slug': 'Slug',
    'categories.description': 'Description',
    'categories.confirmDelete': 'Are you sure you want to delete this category?',
    'categories.uploadFailed': 'Upload failed',

    // Reviews
    'reviews.title': 'Review Management',
    'reviews.totalReviews': 'Total Reviews',
    'reviews.totalLikes': 'Total Likes',
    'reviews.totalShares': 'Total Shares',
    'reviews.reviewsTab': 'Reviews',
    'reviews.likesTab': 'Likes',
    'reviews.sharesTab': 'Shares',
    'reviews.searchPlaceholder': 'Search...',
    'reviews.user': 'User',
    'reviews.product': 'Product',
    'reviews.rating': 'Rating',
    'reviews.count': 'Count',
    'reviews.unknownProduct': 'Unknown Product',
    'reviews.defaultUser': 'Default User',
    'reviews.confirmDelete': 'Confirm delete?',

    // Payments
    'payments.title': 'Payment Management',
    'payments.fee': 'Fee: {percent}% + ${fixed}',
    'payments.apiKey': 'API Key',
    'payments.apiSecret': 'API Secret',
    'payments.apiKeyPlaceholder': 'Enter API Key',
    'payments.apiSecretPlaceholder': 'Enter API Secret',
    'payments.feePercent': 'Fee Percent (%)',
    'payments.fixedFee': 'Fixed Fee ($)',

    // Admins
    'admins.title': 'Admin Management',
    'admins.addAdmin': 'Add Admin',
    'admins.editAdmin': 'Edit Admin',
    'admins.username': 'Username',
    'admins.role': 'Role',
    'admins.status': 'Status',
    'admins.createdAt': 'Created At',
    'admins.actions': 'Actions',
    'admins.passwordLabel': 'Password',
    'admins.passwordHint': '(Leave blank if not changing)',
    'admins.roleAdmin': 'Admin',
    'admins.roleSuperAdmin': 'Super Admin',
    'admins.confirmDelete': 'Confirm delete this admin?',

    // Overview / Stats
    'stats.title': 'Data Overview',
    'stats.totalUsers': 'Total Users',
    'stats.totalOrders': 'Total Orders',
    'stats.totalProducts': 'Total Products',
    'stats.totalReviews': 'Total Reviews',
    'stats.totalSales': 'Total Sales',
    'stats.conversionRate': 'Conversion Rate',
    'stats.salesTrend': 'Sales Trend',
    'stats.userGrowth': 'User Growth',
    'stats.activeUsers': 'Active Users',
    'stats.potentialUsers': 'Potential Users',
    'stats.mon': 'Mon',

    // Detail Pages
    'detailPages.title': 'Product Detail Pages',
    'detailPages.productId': 'Product ID',
    'detailPages.status': 'Status',
    'detailPages.actions': 'Actions',
    'detailPages.edit': 'Edit',

    // Language toggle
    'lang.en': 'EN',
    'lang.zh': '中文',
  },
  zh: {
    // Sidebar
    'admin.title': '管理后台',
    'admin.logout': '退出登录',
    'menu.dashboard': '仪表盘',
    'menu.overview': '概览',
    'menu.traffic': '流量统计',
    'menu.sales': '订单管理',
    'menu.products': '商品管理',
    'menu.banners': '轮播管理',
    'menu.categories': '分类管理',
    'menu.users': '用户管理',
    'menu.reviews': '评论管理',
    'menu.payments': '支付设置',
    'menu.admins': '管理员',

    // Common
    'common.save': '保存',
    'common.saveChanges': '保存更改',
    'common.saving': '保存中...',
    'common.saved': '已保存',
    'common.cancel': '取消',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.add': '添加',
    'common.search': '搜索...',
    'common.loading': '加载中...',
    'common.actions': '操作',
    'common.status': '状态',
    'common.name': '名称',
    'common.active': '启用',
    'common.inactive': '停用',
    'common.yes': '是',
    'common.no': '否',
    'common.back': '返回',
    'common.create': '创建',
    'common.upload': '上传',
    'common.remove': '移除',
    'common.confirm': '确认',
    'common.total': '总计',
    'common.date': '日期',
    'common.amount': '金额',
    'common.close': '关闭',
    'common.noData': '暂无数据',
    'common.na': '暂无',
    'common.enable': '启用',
    'common.disable': '禁用',
    'common.deactivate': '停用',
    'common.activate': '启用',
    'common.more': '更多',
    'common.uploading': '上传中...',
    'common.operationFailed': '操作失败：',
    'common.previous': '上一页',
    'common.next': '下一页',
    'common.pageOf': '第 {current} 页 / 共 {total} 页',
    'common.totalItems': '共 {total} 项',
    'common.perPage': '每页：',
    'common.allCategories': '全部分类',
    'common.image': '图片',
    'common.sortOrder': '排序',
    'common.enabled': '已启用',
    'common.disabled': '已禁用',
    'common.testMode': '测试模式',
    'common.editSettings': '编辑设置',
    'common.editSettingsFor': '编辑 {name} 设置',
    'common.cover': '封面',
    'common.moveLeft': '左移',
    'common.moveRight': '右移',
    'common.moveUp': '上移',
    'common.moveDown': '下移',
    'common.preview': '预览',
    'common.copyLink': '复制链接',

    // Dashboard / Traffic
    'dashboard.title': '流量仪表盘',
    'dashboard.statsTime': '统计时间',
    'dashboard.realtime': '实时',
    'dashboard.7days': '7天',
    'dashboard.30days': '30天',
    'dashboard.day': '今日',
    'dashboard.week': '本周',
    'dashboard.month': '本月',
    'dashboard.exportData': '导出数据',
    'dashboard.trafficOverview': '流量概览',
    'dashboard.visitorAnalysis': '访客分析 >',
    'dashboard.timeTrend': '时间趋势',
    'dashboard.allDevices': '全部设备',
    'dashboard.visitors': '访客数',
    'dashboard.productViews': '商品浏览',
    'dashboard.productVisitors': '商品访客',
    'dashboard.conversion': '转化率',
    'dashboard.payingCustomers': '付费客户',
    'dashboard.storeFollowers': '店铺关注',
    'dashboard.liveVisitors': '实时访客',
    'dashboard.live': '实时',
    'dashboard.shortVideo': '短视频',
    'dashboard.video': '视频',
    'dashboard.imageText': '图文',
    'dashboard.storePage': '店铺页面',
    'dashboard.trafficSources': '流量来源',
    'dashboard.topProducts': '热门商品 TOP10',
    'dashboard.trend24h': '24小时流量趋势',
    'dashboard.people': '人',
    'dashboard.vsYesterday': '较昨日同时段',
    'dashboard.vsPreviousDay': '较前日',
    'dashboard.pageViews': '页面浏览',
    'dashboard.avgPagesSession': '平均访问页数',
    'dashboard.returningVisitors': '回访访客',
    'dashboard.newVisitors': '新访客',

    // Users
    'users.title': '用户管理',
    'users.totalUsers': '总用户数',
    'users.newThisMonth': '本月新增',
    'users.activeUsers': '活跃用户',
    'users.searchPlaceholder': '搜索用户...',
    'users.username': '用户名',
    'users.email': '邮箱',
    'users.phone': '手机号',
    'users.registered': '注册时间',
    'users.role': '角色',

    // Products
    'products.title': '商品管理',
    'products.addProduct': '添加商品',
    'products.editProduct': '编辑商品',
    'products.searchPlaceholder': '搜索商品...',
    'products.productInfo': '商品信息',
    'products.category': '分类',
    'products.selectCategory': '选择分类',
    'products.stock': '库存',
    'products.price': '价格',
    'products.sales': '销量',
    'products.basicInfo': '基本信息',
    'products.pricing': '价格设置',
    'products.images': '商品图片',
    'products.noImages': '暂无图片',
    'products.noImage': '暂无图片',
    'products.features': '产品特点',
    'products.featurePlaceholder': '特点描述',
    'products.addFeature': '+ 添加特点',
    'products.boxContents': '包装内容',
    'products.boxContentPlaceholder': '物品名称',
    'products.addBoxItem': '+ 添加物品',
    'products.detailContent': '商品详情',
    'products.saveDetails': '保存详情',
    'products.editDetails': '编辑详情',
    'products.noProducts': '暂无商品',
    'products.productName': '商品名称',
    'products.slug': 'URL 别名',
    'products.priceCny': '价格 (CNY ¥)',
    'products.originalPriceCny': '原价 (CNY ¥)',
    'products.shortDescription': '简短描述',
    'products.description': '描述',
    'products.fullDescription': '详细描述',
    'products.shortDescPlaceholder': '简要商品描述...',
    'products.descPlaceholder': '详细商品描述...',
    'products.uploadImages': '上传图片',
    'products.imagesUploaded': '张图片已上传',
    'products.deleteImage': '删除图片',
    'products.imageNumber': '图片 {n}',
    'products.priceHint': '输入人民币价格，自动换算为美元存储',
    'products.fetchingRate': '获取汇率中...',
    'products.ratePreview': '1 CNY ≈ {rate} USD',
    'products.refetchRate': '重新获取',
    'products.cnyPlaceholder': '人民币金额',
    'products.usdPreview': '≈ ${amount} USD',
    'products.confirmDelete': '确定要删除此商品吗？',
    'products.confirmBatchDelete': '确定要删除选中的 {count} 件商品吗？此操作不可撤销。',
    'products.batchDeleteFailed': '批量删除失败：',
    'products.selectedCount': '已选择 {count} 项',
    'products.deleteSelected': '删除所选 ({count})',
    'products.uploadFailed': '上传失败：',
    'products.imageError': '错误',
    'products.active': '上架',
    'products.totalStock': '总库存',
    'products.totalSales': '总销量',
    'products.createdAt': '创建时间',
    'products.inStock': '有货',
    'products.totalProducts': '共 {count} 件商品',
    'products.perPageOption': '每页 {n} 条',
    'products.id': 'ID:',
    'products.imagesCount': '张图',
    'products.featuresCount': '个特点',
    'products.productNotFound': '未找到商品',
    'products.requiredFields': '请填写必填项（名称、别名、价格）',
    'products.detailSaveFailed': '详情内容保存失败：',
    'products.visibleToCustomers': '对客户可见',
    'products.hiddenFromStore': '从商店隐藏',
    'products.uploadedCount': '已上传 {count} 张',
    'products.clickToUploadImages': '点击上传商品图片',
    'products.imageUploadHint': '支持 PNG、JPG、GIF，单张最大 5MB',
    'products.itemsCount': '{count} 项',
    'products.imageBlock': '图片区块',
    'products.textBlock': '文本区块',
    'products.blocksCount': '{count} 个区块',
    'products.addImageBlock': '添加图片区块',
    'products.addTextBlock': '添加文本区块',
    'products.clickUploadImage': '点击上传图片',
    'products.featureIndex': '特点 {n}',
    'products.boxItemIndex': '包装项 {n}',
    'common.saveFailed': '保存失败：',

    // Orders
    'orders.title': '销售分析',
    'orders.searchPlaceholder': '搜索订单...',
    'orders.orderNo': '订单号',
    'orders.customer': '客户',
    'orders.amount': '金额',
    'orders.pcs': '件',
    'orders.paid': '✓ 已付款',
    'orders.unpaid': '○ 未付款',
    'orders.orderPrefix': '订单：',
    'orders.customerLabel': '客户：',
    'orders.emailLabel': '邮箱：',
    'orders.phoneLabel': '电话：',
    'orders.addressLabel': '地址：',
    'orders.amountLabel': '金额：',
    'orders.paymentLabel': '支付：',
    'orders.updateStatus': '更新订单状态',
    'orders.updatePaymentStatus': '更新支付状态',
    'orders.markPaid': '✓ 标记已付款',
    'orders.markUnpaid': '○ 标记未付款',
    'orders.pending': '待处理',
    'orders.confirmed': '已确认',
    'orders.completed': '已完成',
    'orders.cancelled': '已取消',

    // Banners
    'banners.title': '轮播管理',
    'banners.addBanner': '添加轮播',
    'banners.editBanner': '编辑轮播',
    'banners.titleLabel': '标题',
    'banners.subtitleLabel': '副标题',
    'banners.imageUrl': '图片链接',
    'banners.link': '跳转链接',
    'banners.sortOrderLabel': '排序',
    'banners.confirmDelete': '确定要删除此轮播吗？',

    // Categories
    'categories.title': '分类管理',
    'categories.addCategory': '添加分类',
    'categories.editCategory': '编辑分类',
    'categories.categoryImage': '分类图片',
    'categories.clickUpload': '点击上传图片',
    'categories.slug': 'URL 别名',
    'categories.description': '描述',
    'categories.confirmDelete': '确定要删除此分类吗？',
    'categories.uploadFailed': '上传失败',

    // Reviews
    'reviews.title': '评论管理',
    'reviews.totalReviews': '总评论数',
    'reviews.totalLikes': '总点赞数',
    'reviews.totalShares': '总分享数',
    'reviews.reviewsTab': '评论',
    'reviews.likesTab': '点赞',
    'reviews.sharesTab': '分享',
    'reviews.searchPlaceholder': '搜索...',
    'reviews.user': '用户',
    'reviews.product': '商品',
    'reviews.rating': '评分',
    'reviews.count': '数量',
    'reviews.unknownProduct': '未知商品',
    'reviews.defaultUser': '默认用户',
    'reviews.confirmDelete': '确定删除？',

    // Payments
    'payments.title': '支付管理',
    'payments.fee': '费率：{percent}% + ${fixed}',
    'payments.apiKey': 'API 密钥',
    'payments.apiSecret': 'API 密文',
    'payments.apiKeyPlaceholder': '请输入 API 密钥',
    'payments.apiSecretPlaceholder': '请输入 API 密文',
    'payments.feePercent': '费率百分比 (%)',
    'payments.fixedFee': '固定费用 ($)',

    // Admins
    'admins.title': '管理员管理',
    'admins.addAdmin': '添加管理员',
    'admins.editAdmin': '编辑管理员',
    'admins.username': '用户名',
    'admins.role': '角色',
    'admins.status': '状态',
    'admins.createdAt': '创建时间',
    'admins.actions': '操作',
    'admins.passwordLabel': '密码',
    'admins.passwordHint': '（不修改请留空）',
    'admins.roleAdmin': '管理员',
    'admins.roleSuperAdmin': '超级管理员',
    'admins.confirmDelete': '确定删除此管理员？',

    // Overview / Stats
    'stats.title': '数据概览',
    'stats.totalUsers': '总用户数',
    'stats.totalOrders': '总订单数',
    'stats.totalProducts': '总商品数',
    'stats.totalReviews': '总评论数',
    'stats.totalSales': '总销售额',
    'stats.conversionRate': '转化率',
    'stats.salesTrend': '销售趋势',
    'stats.userGrowth': '用户增长',
    'stats.activeUsers': '活跃用户',
    'stats.potentialUsers': '潜在用户',
    'stats.mon': '月',

    // Detail Pages
    'detailPages.title': '商品详情页',
    'detailPages.productId': '商品 ID',
    'detailPages.status': '状态',
    'detailPages.actions': '操作',
    'detailPages.edit': '编辑',

    // Language toggle
    'lang.en': 'EN',
    'lang.zh': '中文',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    return (localStorage.getItem('admin_lang') as Lang) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('admin_lang', lang);
  }, [lang]);

  const setLang = (newLang: Lang) => {
    setLangState(newLang);
  };

  const t = (key: string): string => {
    return translations[lang]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
