-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

DROP POLICY IF EXISTS "用户可查看自己的资料" ON profiles;
DROP POLICY IF EXISTS "用户可更新自己的资料" ON profiles;

CREATE POLICY "允许匿名插入资料" ON profiles FOR INSERT WITH CHECK (true);
CREATE POLICY "允许匿名查看资料" ON profiles FOR SELECT USING (true);
CREATE POLICY "允许匿名更新资料" ON profiles FOR UPDATE USING (true);

DROP POLICY IF EXISTS "用户可查看自己的角色" ON user_roles;

CREATE POLICY "允许匿名插入角色" ON user_roles FOR INSERT WITH CHECK (true);
CREATE POLICY "允许匿名查看角色" ON user_roles FOR SELECT USING (true);