-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

CREATE TABLE IF NOT EXISTS payment_gateways (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(100) NOT NULL,
  code VARCHAR(50) UNIQUE NOT NULL,
  icon VARCHAR(50),
  is_active BOOLEAN DEFAULT false,
  api_key TEXT,
  api_secret TEXT,
  fee_percent DECIMAL(5,2) DEFAULT 0,
  fee_fixed DECIMAL(10,2) DEFAULT 0,
  test_mode BOOLEAN DEFAULT true,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

INSERT INTO payment_gateways (name, code, icon, is_active, fee_percent, fee_fixed, test_mode, sort_order) VALUES
('信用卡', 'credit_card', 'CreditCard', true, 2.9, 0.30, true, 1),
('PayPal', 'paypal', 'Wallet', false, 3.4, 0.30, true, 2),
('支付宝', 'alipay', 'Smartphone', false, 0.6, 0, true, 3),
('微信支付', 'wechat', 'Smartphone', false, 0.6, 0, true, 4)
ON CONFLICT (code) DO NOTHING;

ALTER TABLE payment_gateways ENABLE ROW LEVEL SECURITY;

CREATE POLICY "允许匿名用户查看启用的支付网关" ON payment_gateways FOR SELECT USING (is_active = true);
CREATE POLICY "允许管理员管理支付网关" ON payment_gateways FOR ALL USING (true);