-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

ALTER TABLE products ADD COLUMN likes_count INTEGER DEFAULT 0;
ALTER TABLE products ADD COLUMN shares_count INTEGER DEFAULT 0;

CREATE TABLE product_likes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id UUID REFERENCES products(id) ON DELETE CASCADE,
  user_id TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(product_id, user_id)
);

CREATE TABLE product_shares (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id UUID REFERENCES products(id) ON DELETE CASCADE,
  platform TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE product_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_shares ENABLE ROW LEVEL SECURITY;

CREATE POLICY "所有人可查看点赞" ON product_likes FOR SELECT USING (true);
CREATE POLICY "所有人可点赞" ON product_likes FOR INSERT WITH CHECK (true);
CREATE POLICY "所有人可查看分享" ON product_shares FOR SELECT USING (true);
CREATE POLICY "所有人可分享" ON product_shares FOR INSERT WITH CHECK (true);