-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 创建存储桶用于分类图片
INSERT INTO storage.buckets (id, name, public)
VALUES ('categories', 'categories', true)
ON CONFLICT (id) DO NOTHING;

-- 设置存储桶的RLS策略
CREATE POLICY "公开访问分类图片" ON storage.objects
FOR SELECT USING (bucket_id = 'categories');

CREATE POLICY "管理员上传分类图片" ON storage.objects
FOR INSERT WITH CHECK (bucket_id = 'categories');

CREATE POLICY "管理员删除分类图片" ON storage.objects
FOR DELETE USING (bucket_id = 'categories');