-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 产品分类表
CREATE TABLE IF NOT EXISTS public.categories (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  description TEXT,
  image_url TEXT,
  sort_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 产品表
CREATE TABLE IF NOT EXISTS public.products (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  description TEXT,
  short_description TEXT,
  price DECIMAL(10,2) NOT NULL,
  original_price DECIMAL(10,2),
  stock INTEGER DEFAULT 0,
  category_id UUID REFERENCES public.categories(id) ON DELETE SET NULL,
  images TEXT[] DEFAULT '{}',
  features TEXT[] DEFAULT '{}',
  specifications JSONB DEFAULT '{}',
  is_featured BOOLEAN DEFAULT false,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 订单表
CREATE TABLE IF NOT EXISTS public.orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_number TEXT UNIQUE NOT NULL,
  customer_name TEXT NOT NULL,
  customer_email TEXT NOT NULL,
  customer_phone TEXT,
  shipping_address TEXT NOT NULL,
  total_amount DECIMAL(10,2) NOT NULL,
  status TEXT DEFAULT 'pending',
  payment_status TEXT DEFAULT 'unpaid',
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 订单详情表
CREATE TABLE IF NOT EXISTS public.order_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id UUID REFERENCES public.orders(id) ON DELETE CASCADE,
  product_id UUID REFERENCES public.products(id) ON DELETE SET NULL,
  product_name TEXT NOT NULL,
  quantity INTEGER NOT NULL,
  unit_price DECIMAL(10,2) NOT NULL,
  total_price DECIMAL(10,2) NOT NULL
);

-- 管理员表
CREATE TABLE IF NOT EXISTS public.admins (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  role TEXT DEFAULT 'editor',
  is_active BOOLEAN DEFAULT true,
  last_login TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 轮播图表
CREATE TABLE IF NOT EXISTS public.banners (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  subtitle TEXT,
  image_url TEXT NOT NULL,
  link_url TEXT,
  position TEXT DEFAULT 'home',
  sort_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 用户评价表
CREATE TABLE IF NOT EXISTS public.reviews (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_name TEXT NOT NULL,
  location TEXT,
  rating INTEGER DEFAULT 5,
  content TEXT NOT NULL,
  is_featured BOOLEAN DEFAULT false,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 启用RLS
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.banners ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- 公开访问策略
CREATE POLICY "公开查看分类" ON public.categories FOR SELECT USING (is_active = true);
CREATE POLICY "公开查看产品" ON public.products FOR SELECT USING (is_active = true);
CREATE POLICY "公开查看轮播图" ON public.banners FOR SELECT USING (is_active = true);
CREATE POLICY "公开查看评价" ON public.reviews FOR SELECT USING (is_active = true);

-- 管理员策略（通过Edge Function验证）
CREATE POLICY "管理员管理所有数据" ON public.categories FOR ALL USING (true);
CREATE POLICY "管理员管理所有产品" ON public.products FOR ALL USING (true);
CREATE POLICY "管理员管理所有订单" ON public.orders FOR ALL USING (true);
CREATE POLICY "管理员管理订单详情" ON public.order_items FOR ALL USING (true);
CREATE POLICY "管理员管理轮播图" ON public.banners FOR ALL USING (true);
CREATE POLICY "管理员管理评价" ON public.reviews FOR ALL USING (true);

-- 插入默认管理员
INSERT INTO public.admins (username, password_hash, role) 
VALUES ('admin', crypt('admin123', gen_salt('bf')), 'superadmin')
ON CONFLICT (username) DO NOTHING;

-- 插入默认分类
INSERT INTO public.categories (name, slug, description, sort_order) VALUES
('设备', 'devices', 'OOKA电子烟设备', 1),
('烟弹', 'pods', '各种口味烟弹', 2),
('配件', 'accessories', '设备配件', 3)
ON CONFLICT (slug) DO NOTHING;

-- 插入默认轮播图
INSERT INTO public.banners (title, subtitle, image_url, link_url, position, sort_order) VALUES
('OOKA entdecken', 'Erste Shisha Ohne Kohle', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', '/products/devices', 'home', 1),
('OOKA Pods entdecken', 'Beste Shisha Marken', 'https://images.unsplash.com/photo-1560526861-7a63f73c0f5e?w=800', '/products/pods', 'home', 2),
('Finde OOKA', 'Finde OOKA in der Nähe', 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800', '/find-store', 'home', 3)
ON CONFLICT DO NOTHING;

-- 插入默认评价
INSERT INTO public.reviews (customer_name, location, rating, content, is_featured) VALUES
('Lisa', 'Berlin', 5, 'Erstaunliche Entdeckung. So viel sauberer und einfacher als eine herkömmliche Shisha. Ideal für einen ruhigen Abend zu Hause oder nach einem netten Abendessen mit Freunden.', true),
('Mahmoud R.', 'Dubai', 5, 'ERSTAUNLICHE ERFINDUNG! Die Erfahrung hat alle Erwartungen übertroffen, ich liebe es einfach. Die Idee, eine Shisha ohne die lästige Kohle zu rauchen, ist erstaunlich.', true),
('Matt D.', 'München', 5, 'Vergesse den Ärger mit Kohle und Asche - das ist eine Wasserpfeife ohne Aufräumen. Ein echter Wendepunkt.', true)
ON CONFLICT DO NOTHING;