-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

INSERT INTO profiles (id, username, email, created_at)
SELECT 
  id,
  COALESCE(raw_user_meta_data->>'username', split_part(email, '@', 1)),
  email,
  created_at
FROM auth.users
WHERE NOT EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.users.id);

INSERT INTO user_roles (user_id, role)
SELECT id, 'user'
FROM auth.users
WHERE NOT EXISTS (SELECT 1 FROM user_roles WHERE user_roles.user_id = auth.users.id);