-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

CREATE TABLE IF NOT EXISTS admins (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  username VARCHAR(100) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL DEFAULT 'admin',
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

INSERT INTO admins (username, password_hash, role, is_active) 
VALUES ('admin', crypt('admin123', gen_salt('bf')), 'superadmin', true)
ON CONFLICT (username) DO NOTHING;

ALTER TABLE admins ENABLE ROW LEVEL SECURITY;

CREATE POLICY "超级管理员可查看所有管理员" ON admins FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM admins WHERE username = current_setting('app.current_user', true) AND role = 'superadmin'
  )
);

CREATE POLICY "超级管理员可创建管理员" ON admins FOR INSERT WITH CHECK (
  EXISTS (
    SELECT 1 FROM admins WHERE username = current_setting('app.current_user', true) AND role = 'superadmin'
  )
);

CREATE POLICY "超级管理员可更新管理员" ON admins FOR UPDATE USING (
  EXISTS (
    SELECT 1 FROM admins WHERE username = current_setting('app.current_user', true) AND role = 'superadmin'
  )
);

CREATE POLICY "超级管理员可删除管理员" ON admins FOR DELETE USING (
  EXISTS (
    SELECT 1 FROM admins WHERE username = current_setting('app.current_user', true) AND role = 'superadmin'
  )
);