-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

ALTER TABLE product_views ADD COLUMN IF NOT EXISTS view_date DATE DEFAULT CURRENT_DATE;

UPDATE product_views SET view_date = CURRENT_DATE WHERE view_date IS NULL;