-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 用户注册统计表
CREATE TABLE user_registration_stats (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  date DATE NOT NULL UNIQUE,
  daily_count INTEGER DEFAULT 0,
  weekly_count INTEGER DEFAULT 0,
  monthly_count INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 用户活跃统计表
CREATE TABLE user_activity_stats (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  last_active_at TIMESTAMP DEFAULT NOW(),
  login_count INTEGER DEFAULT 0,
  total_session_time INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 用户地域分布表
CREATE TABLE user_geo_distribution (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  province VARCHAR(100),
  city VARCHAR(100),
  user_count INTEGER DEFAULT 0,
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 渠道来源统计表
CREATE TABLE user_channel_stats (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  channel VARCHAR(100) NOT NULL UNIQUE,
  user_count INTEGER DEFAULT 0,
  conversion_rate DECIMAL(5,2) DEFAULT 0,
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 禁用RLS
ALTER TABLE user_registration_stats DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_activity_stats DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_geo_distribution DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_channel_stats DISABLE ROW LEVEL SECURITY;