-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

CREATE TABLE IF NOT EXISTS addresses (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name VARCHAR(100) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  province VARCHAR(50) NOT NULL,
  city VARCHAR(50) NOT NULL,
  district VARCHAR(50) NOT NULL,
  detail_address TEXT NOT NULL,
  is_default BOOLEAN DEFAULT false,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE addresses ENABLE ROW LEVEL SECURITY;

CREATE POLICY "用户查看自己的地址" ON addresses FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "用户创建地址" ON addresses FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "用户更新自己的地址" ON addresses FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "用户删除自己的地址" ON addresses FOR DELETE USING (auth.uid() = user_id);