-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

ALTER TABLE product_likes ADD COLUMN IF NOT EXISTS username TEXT DEFAULT '默认用户';
ALTER TABLE product_shares ADD COLUMN IF NOT EXISTS username TEXT DEFAULT '默认用户';
ALTER TABLE product_shares ADD COLUMN IF NOT EXISTS user_id TEXT;