-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

CREATE TABLE IF NOT EXISTS product_views (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  user_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  session_id TEXT,
  view_count INTEGER DEFAULT 1,
  last_viewed_at TIMESTAMP DEFAULT NOW(),
  created_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE product_views ENABLE ROW LEVEL SECURITY;

CREATE POLICY "允许匿名查看商品浏览统计" ON product_views FOR SELECT USING (true);
CREATE POLICY "允许匿名创建浏览记录" ON product_views FOR INSERT WITH CHECK (true);
CREATE POLICY "允许匿名更新浏览记录" ON product_views FOR UPDATE USING (true);

CREATE INDEX idx_product_views_product_id ON product_views(product_id);
CREATE INDEX idx_product_views_user_id ON product_views(user_id);
CREATE INDEX idx_product_views_last_viewed ON product_views(last_viewed_at DESC);

CREATE OR REPLACE FUNCTION get_product_view_stats(
  p_time_range TEXT DEFAULT 'day'
)
RETURNS TABLE (
  product_id UUID,
  product_name TEXT,
  product_image TEXT,
  view_count BIGINT,
  unique_visitors BIGINT,
  rank BIGINT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    p.id,
    p.name,
    p.images[1] as product_image,
    COALESCE(SUM(pv.view_count), 0)::BIGINT as view_count,
    COUNT(DISTINCT COALESCE(pv.user_id::TEXT, pv.session_id))::BIGINT as unique_visitors,
    ROW_NUMBER() OVER (ORDER BY COALESCE(SUM(pv.view_count), 0) DESC)::BIGINT as rank
  FROM products p
  LEFT JOIN product_views pv ON p.id = pv.product_id
    AND (
      p_time_range = 'day' AND pv.last_viewed_at >= NOW() - INTERVAL '1 day'
      OR p_time_range = 'week' AND pv.last_viewed_at >= NOW() - INTERVAL '7 days'
      OR p_time_range = 'month' AND pv.last_viewed_at >= NOW() - INTERVAL '30 days'
      OR p_time_range = 'all'
    )
  GROUP BY p.id, p.name, p.images
  ORDER BY view_count DESC
  LIMIT 50;
END;
$$;