-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

DROP POLICY IF EXISTS "用户可查看自己的资料" ON public.profiles;
DROP POLICY IF EXISTS "用户可更新自己的资料" ON public.profiles;
DROP POLICY IF EXISTS "管理员可查看所有用户资料" ON public.profiles;

CREATE POLICY "用户可查看自己的资料" ON public.profiles
  FOR SELECT USING (auth.uid() = id);

CREATE POLICY "用户可更新自己的资料" ON public.profiles
  FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "管理员可查看所有用户资料" ON public.profiles
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.user_roles 
      WHERE user_roles.user_id = auth.uid() AND user_roles.role = 'admin'
    )
  );