-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

DROP POLICY IF EXISTS "超级管理员可查看所有管理员" ON admins;
DROP POLICY IF EXISTS "超级管理员可创建管理员" ON admins;
DROP POLICY IF EXISTS "超级管理员可更新管理员" ON admins;
DROP POLICY IF EXISTS "超级管理员可删除管理员" ON admins;

CREATE POLICY "允许匿名查询管理员" ON admins FOR SELECT USING (true);
CREATE POLICY "超级管理员可创建管理员" ON admins FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM admins WHERE admins.username = current_setting('app.current_user', true) AND admins.role = 'superadmin'));
CREATE POLICY "超级管理员可更新管理员" ON admins FOR UPDATE USING (EXISTS (SELECT 1 FROM admins WHERE admins.username = current_setting('app.current_user', true) AND admins.role = 'superadmin'));
CREATE POLICY "超级管理员可删除管理员" ON admins FOR DELETE USING (EXISTS (SELECT 1 FROM admins WHERE admins.username = current_setting('app.current_user', true) AND admins.role = 'superadmin'));