-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

CREATE TABLE product_detail_pages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id UUID REFERENCES products(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  layout JSONB DEFAULT '{}',
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(product_id)
);

ALTER TABLE product_detail_pages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "所有人可查看产品详情页" ON product_detail_pages FOR SELECT USING (true);
CREATE POLICY "管理员可管理产品详情页" ON product_detail_pages FOR ALL USING (true);