-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

CREATE POLICY "所有人可取消点赞" ON public.product_likes FOR DELETE USING (true);