-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 创建存储桶用于产品图片
INSERT INTO storage.buckets (id, name, public)
VALUES ('products', 'products', true)
ON CONFLICT (id) DO NOTHING;

-- 设置存储桶的RLS策略
CREATE POLICY "公开访问产品图片" ON storage.objects
FOR SELECT USING (bucket_id = 'products');

CREATE POLICY "管理员上传产品图片" ON storage.objects
FOR INSERT WITH CHECK (bucket_id = 'products');

CREATE POLICY "管理员删除产品图片" ON storage.objects
FOR DELETE USING (bucket_id = 'products');