-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

CREATE TABLE IF NOT EXISTS traffic_stats (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  stat_date DATE NOT NULL,
  hour INTEGER,
  page_views INTEGER DEFAULT 0,
  unique_visitors INTEGER DEFAULT 0,
  new_visitors INTEGER DEFAULT 0,
  returning_visitors INTEGER DEFAULT 0,
  product_views INTEGER DEFAULT 0,
  orders_count INTEGER DEFAULT 0,
  paying_customers INTEGER DEFAULT 0,
  avg_pages_per_session DECIMAL(5,2) DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS traffic_sources (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  source_name TEXT NOT NULL,
  stat_date DATE NOT NULL,
  visitors INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE traffic_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE traffic_sources ENABLE ROW LEVEL SECURITY;

CREATE POLICY "允许匿名查看流量统计" ON traffic_stats FOR SELECT USING (true);
CREATE POLICY "允许匿名查看流量来源" ON traffic_sources FOR SELECT USING (true);

CREATE INDEX idx_traffic_stats_date ON traffic_stats(stat_date);
CREATE INDEX idx_traffic_sources_date ON traffic_sources(stat_date);

CREATE OR REPLACE FUNCTION get_traffic_overview(p_time_range TEXT DEFAULT 'day')
RETURNS TABLE (
  metric_name TEXT,
  current_value BIGINT,
  previous_value BIGINT,
  change_percent DECIMAL(5,2)
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN QUERY
  WITH current_period AS (
    SELECT 
      COALESCE(SUM(page_views), 0) as page_views,
      COALESCE(SUM(unique_visitors), 0) as visitors,
      COALESCE(SUM(product_views), 0) as product_views,
      COALESCE(SUM(orders_count), 0) as orders,
      COALESCE(SUM(paying_customers), 0) as paying_customers,
      COALESCE(SUM(new_visitors), 0) as new_visitors,
      COALESCE(SUM(returning_visitors), 0) as returning_visitors,
      CASE WHEN SUM(unique_visitors) > 0 
        THEN ROUND((SUM(page_views)::DECIMAL / SUM(unique_visitors)), 2)
        ELSE 0 
      END as avg_pages
    FROM traffic_stats
    WHERE stat_date >= CASE 
      WHEN p_time_range = 'day' THEN CURRENT_DATE
      WHEN p_time_range = 'week' THEN CURRENT_DATE - INTERVAL '7 days'
      WHEN p_time_range = 'month' THEN CURRENT_DATE - INTERVAL '30 days'
      ELSE CURRENT_DATE - INTERVAL '100 years'
    END
  ),
  previous_period AS (
    SELECT 
      COALESCE(SUM(page_views), 0) as page_views,
      COALESCE(SUM(unique_visitors), 0) as visitors,
      COALESCE(SUM(product_views), 0) as product_views,
      COALESCE(SUM(orders_count), 0) as orders,
      COALESCE(SUM(paying_customers), 0) as paying_customers,
      COALESCE(SUM(new_visitors), 0) as new_visitors,
      COALESCE(SUM(returning_visitors), 0) as returning_visitors,
      CASE WHEN SUM(unique_visitors) > 0 
        THEN ROUND((SUM(page_views)::DECIMAL / SUM(unique_visitors)), 2)
        ELSE 0 
      END as avg_pages
    FROM traffic_stats
    WHERE stat_date >= CASE 
      WHEN p_time_range = 'day' THEN CURRENT_DATE - INTERVAL '1 day'
      WHEN p_time_range = 'week' THEN CURRENT_DATE - INTERVAL '14 days'
      WHEN p_time_range = 'month' THEN CURRENT_DATE - INTERVAL '60 days'
      ELSE CURRENT_DATE - INTERVAL '200 years'
    END
    AND stat_date < CASE 
      WHEN p_time_range = 'day' THEN CURRENT_DATE
      WHEN p_time_range = 'week' THEN CURRENT_DATE - INTERVAL '7 days'
      WHEN p_time_range = 'month' THEN CURRENT_DATE - INTERVAL '30 days'
      ELSE CURRENT_DATE - INTERVAL '100 years'
    END
  )
  SELECT 
    'page_views'::TEXT as metric_name,
    c.page_views::BIGINT as current_value,
    p.page_views::BIGINT as previous_value,
    CASE WHEN p.page_views > 0 
      THEN ROUND(((c.page_views - p.page_views)::DECIMAL / p.page_views * 100), 2)
      ELSE 0 
    END as change_percent
  FROM current_period c, previous_period p
  UNION ALL
  SELECT 
    'visitors'::TEXT,
    c.visitors::BIGINT,
    p.visitors::BIGINT,
    CASE WHEN p.visitors > 0 
      THEN ROUND(((c.visitors - p.visitors)::DECIMAL / p.visitors * 100), 2)
      ELSE 0 
    END
  FROM current_period c, previous_period p
  UNION ALL
  SELECT 
    'product_views'::TEXT,
    c.product_views::BIGINT,
    p.product_views::BIGINT,
    CASE WHEN p.product_views > 0 
      THEN ROUND(((c.product_views - p.product_views)::DECIMAL / p.product_views * 100), 2)
      ELSE 0 
    END
  FROM current_period c, previous_period p
  UNION ALL
  SELECT 
    'orders'::TEXT,
    c.orders::BIGINT,
    p.orders::BIGINT,
    CASE WHEN p.orders > 0 
      THEN ROUND(((c.orders - p.orders)::DECIMAL / p.orders * 100), 2)
      ELSE 0 
    END
  FROM current_period c, previous_period p
  UNION ALL
  SELECT 
    'paying_customers'::TEXT,
    c.paying_customers::BIGINT,
    p.paying_customers::BIGINT,
    CASE WHEN p.paying_customers > 0 
      THEN ROUND(((c.paying_customers - p.paying_customers)::DECIMAL / p.paying_customers * 100), 2)
      ELSE 0 
    END
  FROM current_period c, previous_period p
  UNION ALL
  SELECT 
    'new_visitors'::TEXT,
    c.new_visitors::BIGINT,
    p.new_visitors::BIGINT,
    CASE WHEN p.new_visitors > 0 
      THEN ROUND(((c.new_visitors - p.new_visitors)::DECIMAL / p.new_visitors * 100), 2)
      ELSE 0 
    END
  FROM current_period c, previous_period p
  UNION ALL
  SELECT 
    'returning_visitors'::TEXT,
    c.returning_visitors::BIGINT,
    p.returning_visitors::BIGINT,
    CASE WHEN p.returning_visitors > 0 
      THEN ROUND(((c.returning_visitors - p.returning_visitors)::DECIMAL / p.returning_visitors * 100), 2)
      ELSE 0 
    END
  FROM current_period c, previous_period p
  UNION ALL
  SELECT 
    'avg_pages'::TEXT,
    (c.avg_pages * 100)::BIGINT,
    (p.avg_pages * 100)::BIGINT,
    CASE WHEN p.avg_pages > 0 
      THEN ROUND(((c.avg_pages - p.avg_pages)::DECIMAL / p.avg_pages * 100), 2)
      ELSE 0 
    END
  FROM current_period c, previous_period p;
END;
$$;