/**
 * 🚨 此文件由 CloudEnableTool 自动生成，请勿手动修改！
 * This file is auto-generated by CloudEnableTool. Do not edit manually!
 */

import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export function getSupabaseUrl(): string {
  return 'https://ncncgpmfkgccsgkbuqss.supabase.co';
}

export const supabaseUrl = getSupabaseUrl();
export const supabaseAnonKey = 'sb_publishable_gu9p9y0Xe5p3dYolh031pQ_qzyUBH3K';

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
});
